### ISSUE TITLE
we need gpu gc when complete use model

### ISSUE THREAD

**Issue by kylelee** [huajianmao/llm-as-openai#1]
I have wrote a new function gpu.gc

**Comment by kylelee** [comment]
`
import gc
import torch

def gpu_gc():
    gc.collect()
    if torch.cuda.is_available():
        # with torch.cuda.device(DEVICE):
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()
    elif torch.backends.mps.is_available():
        try:
            from torch.mps import empty_cache
            empty_cache()
        except Exception as e:
            print(e)
            print("if you are on macOS, suggest upgrade pytorch >= 2.0.0")
`

**Comment by huajianmao** [comment]
Thanks for your suggestion.

We have gc for cuda in [`lifespan`](https://fastapi.tiangolo.com/advanced/events/#lifespan-events) with the code after the [`yield`](https://github.com/huajianmao/llm-as-openai/commit/81d6cc9f6f8490040bcb41dca83a29fcbdb90880#diff-d1f0f72ecbf1b8b4722b31c67c986a63dfaf0614dcf4ee3c77022ba76b38b3deL27).
And I have added gc for the mps device according to your suggestion in the commit 81d6cc9.

Thanks.
